I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/lock.rpy", line 1, in script
    init python:
  File "game/lock.rpy", line 14, in <module>
    images_auto()
NameError: name 'images_auto' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/lock.rpy", line 1, in script
    init python:
  File "D:\Soft\RenPy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Soft\RenPy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/lock.rpy", line 14, in <module>
    images_auto()
NameError: name 'images_auto' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Zero Keep Out 1.0
Sun May 19 17:27:34 2024
