I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 152, in script call
    call paralax
  File "game/script.rpy", line 583, in script call
    call рассказать
  File "game/Locations/cafe.rpy", line 2, in script
    scene bg in_cafe with dissolve
Exception: Image 'bg' does not accept attributes 'in_cafe'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 152, in script call
    call paralax
  File "game/script.rpy", line 583, in script call
    call рассказать
  File "game/Locations/cafe.rpy", line 2, in script
    scene bg in_cafe with dissolve
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\ast.py", line 1247, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'bg' does not accept attributes 'in_cafe'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
Zero Keep Out 1.0
Sun May 19 12:54:12 2024
